- name: configure my sql server
  hosts: mysql
  become: yes
  tasks:
  - name:  installing mysql libraries PyMySQL 2.7
    packages:
      name: 
        - PyMySQL
        - python3
        - python3-pip
      state: present
      executable: pip3

  - name: installing mysql server
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start and enable mysql-server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect to mysql mysql-server
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.lokeshportfo.site
    register: mysql_info
    ignore_errors: true
    
  - name: print the output
    ansible.builtin.debug:
      msg: "mysql info {{ mysql_info }}"
